{ lib, pkgs, config, ... }:
{
  programs.alacritty = {
    enable = true;
  };

  home.file.".config/alacritty/alacritty.toml".source = pkgs.writeText "alacritty.toml" ''
      font.size = 11
      shell.program = "${pkgs.fish}/bin/fish"

      # Autogenerated color theming:
      ${builtins.readFile "${alacritty_themes}/themes/alabaster_dark.toml"}
    '';
}
